/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITelepathyBroadcaster__factory } from "./ITelepathyBroadcaster__factory";
export { ITelepathyHandler__factory } from "./ITelepathyHandler__factory";
export { ITelepathyReceiver__factory } from "./ITelepathyReceiver__factory";
