/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITelepathyBroadcaster } from "./ITelepathyBroadcaster";
export type { ITelepathyHandler } from "./ITelepathyHandler";
export type { ITelepathyReceiver } from "./ITelepathyReceiver";
