/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as crossChainMailboxSol from "./CrossChainMailbox.sol";
export * as iTelepathySol from "./ITelepathy.sol";
