/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iTelepathySol from "./ITelepathy.sol";
export { CrossChainMailbox__factory } from "./CrossChainMailbox__factory";
export { CrossChainMailer__factory } from "./CrossChainMailer__factory";
