/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iTelepathySol from "./ITelepathy.sol";
export type { iTelepathySol };
export type { CrossChainMailbox } from "./CrossChainMailbox";
export * as factories from "./factories";
export { CrossChainMailbox__factory } from "./factories/CrossChainMailbox__factory";
export type { ITelepathyBroadcaster } from "./ITelepathy.sol/ITelepathyBroadcaster";
export { ITelepathyBroadcaster__factory } from "./factories/ITelepathy.sol/ITelepathyBroadcaster__factory";
export type { ITelepathyHandler } from "./ITelepathy.sol/ITelepathyHandler";
export { ITelepathyHandler__factory } from "./factories/ITelepathy.sol/ITelepathyHandler__factory";
export type { ITelepathyReceiver } from "./ITelepathy.sol/ITelepathyReceiver";
export { ITelepathyReceiver__factory } from "./factories/ITelepathy.sol/ITelepathyReceiver__factory";
