/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface ITelepathyBroadcasterInterface extends utils.Interface {
  functions: {
    "send(uint32,address,bytes)": FunctionFragment;
    "send(uint32,bytes32,bytes)": FunctionFragment;
    "sendViaStorage(uint32,address,bytes)": FunctionFragment;
    "sendViaStorage(uint32,bytes32,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "send(uint32,address,bytes)"
      | "send(uint32,bytes32,bytes)"
      | "sendViaStorage(uint32,address,bytes)"
      | "sendViaStorage(uint32,bytes32,bytes)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "send(uint32,address,bytes)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "send(uint32,bytes32,bytes)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sendViaStorage(uint32,address,bytes)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sendViaStorage(uint32,bytes32,bytes)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "send(uint32,address,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "send(uint32,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendViaStorage(uint32,address,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendViaStorage(uint32,bytes32,bytes)",
    data: BytesLike
  ): Result;

  events: {
    "SentMessage(uint64,bytes32,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SentMessage"): EventFragment;
}

export interface SentMessageEventObject {
  nonce: BigNumber;
  msgHash: string;
  message: string;
}
export type SentMessageEvent = TypedEvent<
  [BigNumber, string, string],
  SentMessageEventObject
>;

export type SentMessageEventFilter = TypedEventFilter<SentMessageEvent>;

export interface ITelepathyBroadcaster extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITelepathyBroadcasterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    "send(uint32,address,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "send(uint32,bytes32,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<BytesLike>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "sendViaStorage(uint32,address,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "sendViaStorage(uint32,bytes32,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<BytesLike>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  "send(uint32,address,bytes)"(
    recipientChainId: PromiseOrValue<BigNumberish>,
    recipientAddress: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "send(uint32,bytes32,bytes)"(
    recipientChainId: PromiseOrValue<BigNumberish>,
    recipientAddress: PromiseOrValue<BytesLike>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "sendViaStorage(uint32,address,bytes)"(
    recipientChainId: PromiseOrValue<BigNumberish>,
    recipientAddress: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "sendViaStorage(uint32,bytes32,bytes)"(
    recipientChainId: PromiseOrValue<BigNumberish>,
    recipientAddress: PromiseOrValue<BytesLike>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    "send(uint32,address,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    "send(uint32,bytes32,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<BytesLike>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    "sendViaStorage(uint32,address,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    "sendViaStorage(uint32,bytes32,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<BytesLike>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "SentMessage(uint64,bytes32,bytes)"(
      nonce?: PromiseOrValue<BigNumberish> | null,
      msgHash?: PromiseOrValue<BytesLike> | null,
      message?: null
    ): SentMessageEventFilter;
    SentMessage(
      nonce?: PromiseOrValue<BigNumberish> | null,
      msgHash?: PromiseOrValue<BytesLike> | null,
      message?: null
    ): SentMessageEventFilter;
  };

  estimateGas: {
    "send(uint32,address,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "send(uint32,bytes32,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<BytesLike>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "sendViaStorage(uint32,address,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "sendViaStorage(uint32,bytes32,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<BytesLike>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    "send(uint32,address,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "send(uint32,bytes32,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<BytesLike>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "sendViaStorage(uint32,address,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "sendViaStorage(uint32,bytes32,bytes)"(
      recipientChainId: PromiseOrValue<BigNumberish>,
      recipientAddress: PromiseOrValue<BytesLike>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
