export const links = {
  docs: "https://docs.succinct.xyz/",
  explorer: "https://scan.succinct.xyz/",
  careers: "https://jobs.ashbyhq.com/succinct",
  blog: "https://blog.succinct.xyz/",
  demo: "https://demo.telepathy.xyz/",
  partner: "https://airtable.com/shrKT6HrHi2oDcmrf",
  terms: "#",
  privacy: "#",
  twitter: "https://twitter.com/succinctlabs",
  discord: "https://discord.gg/succinctlabs",
  github: "https://github.com/succinctlabs",
  audit: "#",
  faq: "#",
  telepathy: "/telepathy",
  home: "https://succinct.xyz/",
};
